<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>12</LangVersion>
    <IsPackable>false</IsPackable>
    <SignAssembly>false</SignAssembly>
    <AnalysisLevel>latest-Default</AnalysisLevel>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <CompilerGeneratedFilesOutputPath>$(BaseIntermediateOutputPath)$(Configuration)/$(TargetFramework)/GeneratedFiles</CompilerGeneratedFilesOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.Memory" />
    <Compile Include="../Parlot.Standalone.Tests/Grammar.cs" Link="Grammar.cs" />
    <AdditionalFiles Include="../Parlot.Standalone.Tests/Grammar.parlot.cs" Link="Grammar.parlot.cs" />
    <ProjectReference Include="../../src/Parlot.SourceGenerator/Parlot.SourceGenerator.csproj"
                      OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    <Analyzer Include="../../src/Parlot/bin/$(Configuration)/netstandard2.0/Parlot.dll" />
  </ItemGroup>
  <Import Project="../../src/Parlot.SourceGenerator/build/Parlot.SourceGenerator.props" />
  <Import Project="../../src/Parlot.SourceGenerator/build/Parlot.SourceGenerator.targets" />
</Project>
