namespace Parlot.SourceGenerator;

/// <summary>
/// Specifies source generator assemblies that should be executed on the compilation before
/// emitting the assembly for parser execution. Use this attribute alongside <see cref="GenerateParserAttribute"/>
/// when your parser code depends on types or code generated by other source generators.
/// </summary>
/// <remarks>
/// <para>
/// Some source generators (like PolySharp for polyfills, or logging generators) produce code
/// that your parser method may depend on. By specifying the generator assembly names, Parlot's
/// source generator will load and run those generators before emitting the compilation.
/// </para>
/// 
/// <para>
/// The assembly names should match the assembly name of the source generator (typically the
/// NuGet package name or the assembly file name without the .dll extension).
/// </para>
/// 
/// Example usage:
/// <code>
/// [GenerateParser]
/// [IncludeGenerators("PolySharp")]
/// public static Parser&lt;Expression&gt; CreateExpressionParser()
/// {
///     // Parser implementation that uses polyfill types from PolySharp
/// }
/// </code>
/// 
/// You can specify multiple generator assemblies:
/// <code>
/// [GenerateParser]
/// [IncludeGenerators("PolySharp", "Microsoft.Extensions.Logging.Generators")]
/// public static Parser&lt;Expression&gt; CreateExpressionParser() =&gt; ...;
/// </code>
/// 
/// You can apply this attribute to methods or container classes:
/// <code>
/// [IncludeGenerators("PolySharp")]
/// public static class MyParsers
/// {
///     [GenerateParser]
///     public static Parser&lt;Expression&gt; ExpressionParser() =&gt; ...;
///     
///     [GenerateParser]
///     [IncludeGenerators("AnotherGenerator")]
///     public static Parser&lt;Statement&gt; StatementParser() =&gt; ...;
/// }
/// </code>
/// 
/// When applied to a class, the generators will be run for all generated parsers within that class.
/// </remarks>
[System.AttributeUsage(System.AttributeTargets.Method | System.AttributeTargets.Class, AllowMultiple = false)]
#if SOURCE_GENERATOR
internal
#else
public
#endif
sealed class IncludeGeneratorsAttribute : System.Attribute
{
    /// <summary>
    /// Gets the assembly names of the source generators to run.
    /// </summary>
    public string[] GeneratorAssemblies { get; }

    /// <summary>
    /// Specifies source generator assemblies to run before emitting the compilation.
    /// </summary>
    /// <param name="generatorAssemblies">
    /// The assembly names of source generators to run (e.g., "PolySharp", "Microsoft.Extensions.Logging.Generators").
    /// These should match the generator assembly names as they appear in analyzer references.
    /// </param>
    public IncludeGeneratorsAttribute(params string[] generatorAssemblies)
    {
        GeneratorAssemblies = generatorAssemblies ?? System.Array.Empty<string>();
    }
}
