using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Parlot.SourceGenerator;

internal static class StandaloneRuntimeSources
{
    private const string ResourcePrefix = "Parlot.StandaloneRuntime.";

    private static readonly string[] SourceNames =
    [
        "Scanner.cs",
        "Cursor.cs",
        "TextPosition.cs",
        "TextSpan.cs",
        "ParseResult.cs",
        "ParseException.cs",
        "ParseError.cs",
        "Option.cs",
        "Character.cs",
        "Character.Class.cs",
        "Character.Generated.cs",
        "Character.Mask.cs",
        "Character.SearchValues.cs",
        "Numbers.cs",
        "HexConverter.cs",
        "ThrowHelper.cs",
        "Polyfills.Numbers.cs",
        "Polyfills.Char.cs",
        "Polyfills.ArgumentNullException.cs",
        "Fluent.ParseContext.cs",
        "Fluent.HybridList.cs",
        "Fluent.NumberOptions.cs",
        "Fluent.DelegateParser.cs",
        "Fluent.Parser.cs",
    ];

    internal static IReadOnlyList<(string HintName, SyntaxTree Tree)> GetSources(CSharpParseOptions options)
    {
        var assembly = typeof(StandaloneRuntimeSources).Assembly;
        var sources = new List<(string HintName, SyntaxTree Tree)>(SourceNames.Length);
        var rewriter = new RuntimeRewriter(rewriteDeclarations: true, downlevel: !options.PreprocessorSymbolNames.Contains("NET8_0_OR_GREATER"));
        using var licenseStream = assembly.GetManifestResourceStream(ResourcePrefix + "License")
            ?? throw new InvalidOperationException("Missing embedded runtime license.");
        using var licenseReader = new StreamReader(licenseStream, Encoding.UTF8);
        var header = "// <auto-generated/>\n/*\n" + licenseReader.ReadToEnd() + "\n*/\n#nullable enable\n";

        foreach (var name in SourceNames)
        {
            using var stream = assembly.GetManifestResourceStream(ResourcePrefix + name)
                ?? throw new InvalidOperationException($"Missing standalone runtime resource '{ResourcePrefix + name}'.");
            using var reader = new StreamReader(stream, Encoding.UTF8);
            var hintName = ResourcePrefix + name.Replace(".cs", ".g.cs");
            var tree = CSharpSyntaxTree.ParseText(reader.ReadToEnd(), options.WithLanguageVersion(LanguageVersion.Latest), hintName, Encoding.UTF8);
            var root = (CompilationUnitSyntax)rewriter.Visit(tree.GetRoot())!;
            var text = header + root.ToFullString();
            sources.Add((hintName, CSharpSyntaxTree.ParseText(text, options, hintName, Encoding.UTF8)));
        }

        return sources;
    }

    internal static string RewriteGeneratedSource(string source, CSharpParseOptions options)
    {
        var tree = CSharpSyntaxTree.ParseText(source, options);
        return new RuntimeRewriter(rewriteDeclarations: false, downlevel: false).Visit(tree.GetRoot())!.ToFullString();
    }

    private sealed class RuntimeRewriter : CSharpSyntaxRewriter
    {
        private readonly bool _rewriteDeclarations;
        private readonly bool _downlevel;

        public RuntimeRewriter(bool rewriteDeclarations, bool downlevel)
        {
            _rewriteDeclarations = rewriteDeclarations;
            _downlevel = downlevel;
        }

        public override SyntaxNode? VisitUsingDirective(UsingDirectiveSyntax node)
        {
            var rewritten = (UsingDirectiveSyntax)base.VisitUsingDirective(node)!;
            if (node.Name is not null && IsRuntimeNamespace(node.Name, out var fluent))
            {
                return rewritten.WithName(RewriteNamespace(node.Name, fluent));
            }

            return rewritten;
        }

        public override SyntaxNode? VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
        {
            var rewritten = (NamespaceDeclarationSyntax)base.VisitNamespaceDeclaration(node)!;
            return _rewriteDeclarations && IsRuntimeNamespace(node.Name, out var fluent)
                ? rewritten.WithName(RewriteNamespace(node.Name, fluent))
                : rewritten;
        }

        public override SyntaxNode? VisitFileScopedNamespaceDeclaration(FileScopedNamespaceDeclarationSyntax node)
        {
            var rewritten = (FileScopedNamespaceDeclarationSyntax)base.VisitFileScopedNamespaceDeclaration(node)!;
            return _rewriteDeclarations && IsRuntimeNamespace(node.Name, out var fluent)
                ? rewritten.WithName(RewriteNamespace(node.Name, fluent))
                : rewritten;
        }

        public override SyntaxNode? VisitQualifiedName(QualifiedNameSyntax node)
        {
            var rewritten = (QualifiedNameSyntax)base.VisitQualifiedName(node)!;
            return IsRuntimeNamespace(node.Left, out var fluent) && IsRuntimeType(node.Right, fluent)
                ? rewritten.WithLeft(RewriteNamespace(node.Left, fluent))
                : rewritten;
        }

        public override SyntaxNode? VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
        {
            var rewritten = (MemberAccessExpressionSyntax)base.VisitMemberAccessExpression(node)!;
            if (_downlevel && node.FirstAncestorOrSelf<ClassDeclarationSyntax>()?.Identifier.ValueText
                is not ("NumberPolyfills" or "CharPolyfills" or "ArgumentNullExceptionPolyfills"))
            {
                var helper = (node.Expression.ToString(), node.Name.Identifier.ValueText) switch
                {
                    ("byte" or "sbyte" or "short" or "ushort" or "int" or "uint" or "long" or "ulong"
                        or "float" or "double" or "decimal" or "BigInteger", "TryParse") => "NumberPolyfills",
                    ("char", "IsAsciiDigit" or "IsAsciiHexDigit") => "CharPolyfills",
                    ("ArgumentNullException", "ThrowIfNull") => "ArgumentNullExceptionPolyfills",
                    _ => null,
                };
                if (helper is not null)
                {
                    return rewritten.WithExpression(SyntaxFactory.IdentifierName(helper).WithTriviaFrom(node.Expression));
                }
            }

            if (!IsRuntimeNamespace(node.Expression, out var fluent) || !IsRuntimeType(node.Name, fluent))
            {
                return rewritten;
            }

            var name = HasGlobalAlias(node.Expression) ? "global::Parlot.Generated" : "Parlot.Generated";
            if (fluent)
            {
                name += ".Fluent";
            }

            return rewritten.WithExpression(SyntaxFactory.ParseExpression(name).WithTriviaFrom(node.Expression));
        }

        public override SyntaxNode? VisitClassDeclaration(ClassDeclarationSyntax node)
        {
            var rewritten = (ClassDeclarationSyntax)base.VisitClassDeclaration(node)!;
            if (_downlevel)
            {
                // Keep one shared implementation while lowering C# 14 static extensions to C# 12.
                var members = new List<MemberDeclarationSyntax>();
                foreach (var member in rewritten.Members)
                {
                    if (member is ExtensionBlockDeclarationSyntax extension)
                    {
                        members.AddRange(extension.Members);
                    }
                    else
                    {
                        members.Add(member);
                    }
                }

                rewritten = rewritten.WithMembers(SyntaxFactory.List(members));
            }

            return IsRuntimeDeclaration(node) ? rewritten.WithModifiers(Internalize(node.Modifiers)) : rewritten;
        }

        public override SyntaxNode? VisitAttributeList(AttributeListSyntax node)
        {
            if (!_downlevel)
            {
                return base.VisitAttributeList(node);
            }

            // These annotations have no runtime behavior, and the generated helpers are internal.
            // Avoid requiring PolySharp or declaring BCL-shaped attributes in the application.
            var attributes = node.Attributes.Where(static attribute =>
                attribute.Name.ToString() is not ("NotNull" or "DoesNotReturn" or "CallerArgumentExpression")).ToArray();
            return attributes.Length == 0 ? null : node.WithAttributes(SyntaxFactory.SeparatedList(attributes));
        }

        public override SyntaxNode? VisitStructDeclaration(StructDeclarationSyntax node)
        {
            var rewritten = (StructDeclarationSyntax)base.VisitStructDeclaration(node)!;
            return IsRuntimeDeclaration(node) ? rewritten.WithModifiers(Internalize(node.Modifiers)) : rewritten;
        }

        public override SyntaxNode? VisitInterfaceDeclaration(InterfaceDeclarationSyntax node)
        {
            var rewritten = (InterfaceDeclarationSyntax)base.VisitInterfaceDeclaration(node)!;
            return IsRuntimeDeclaration(node) ? rewritten.WithModifiers(Internalize(node.Modifiers)) : rewritten;
        }

        public override SyntaxNode? VisitRecordDeclaration(RecordDeclarationSyntax node)
        {
            var rewritten = (RecordDeclarationSyntax)base.VisitRecordDeclaration(node)!;
            return IsRuntimeDeclaration(node) ? rewritten.WithModifiers(Internalize(node.Modifiers)) : rewritten;
        }

        public override SyntaxNode? VisitEnumDeclaration(EnumDeclarationSyntax node)
        {
            var rewritten = (EnumDeclarationSyntax)base.VisitEnumDeclaration(node)!;
            return IsRuntimeDeclaration(node) ? rewritten.WithModifiers(Internalize(node.Modifiers)) : rewritten;
        }

        public override SyntaxNode? VisitDelegateDeclaration(DelegateDeclarationSyntax node)
        {
            var rewritten = (DelegateDeclarationSyntax)base.VisitDelegateDeclaration(node)!;
            return IsRuntimeDeclaration(node) ? rewritten.WithModifiers(Internalize(node.Modifiers)) : rewritten;
        }

        private bool IsRuntimeDeclaration(MemberDeclarationSyntax node)
        {
            return _rewriteDeclarations && node.Parent is BaseNamespaceDeclarationSyntax or CompilationUnitSyntax;
        }

        private static SyntaxTokenList Internalize(SyntaxTokenList modifiers)
        {
            foreach (var modifier in modifiers)
            {
                if (modifier.IsKind(SyntaxKind.PublicKeyword))
                {
                    return modifiers.Replace(modifier, SyntaxFactory.Token(SyntaxKind.InternalKeyword).WithTriviaFrom(modifier));
                }
            }

            // A top-level type without an accessibility modifier is already internal.
            return modifiers;
        }

        private static NameSyntax RewriteNamespace(NameSyntax name, bool fluent)
        {
            var replacement = HasGlobalAlias(name) ? "global::Parlot.Generated" : "Parlot.Generated";
            if (fluent)
            {
                replacement += ".Fluent";
            }

            return SyntaxFactory.ParseName(replacement).WithTriviaFrom(name);
        }

        private static bool HasGlobalAlias(ExpressionSyntax expression)
        {
            return expression switch
            {
                AliasQualifiedNameSyntax alias => alias.Alias.Identifier.ValueText == "global",
                QualifiedNameSyntax qualified => HasGlobalAlias(qualified.Left),
                MemberAccessExpressionSyntax member => HasGlobalAlias(member.Expression),
                _ => false,
            };
        }

        private static bool IsRuntimeNamespace(ExpressionSyntax expression, out bool fluent)
        {
            fluent = false;
            if (IsParlotNamespace(expression))
            {
                return true;
            }

            var isFluent = expression switch
            {
                QualifiedNameSyntax { Right: IdentifierNameSyntax right } qualified
                    => right.Identifier.ValueText == "Fluent" && IsParlotNamespace(qualified.Left),
                MemberAccessExpressionSyntax { Name: IdentifierNameSyntax name } member
                    => name.Identifier.ValueText == "Fluent" && IsParlotNamespace(member.Expression),
                _ => false,
            };

            fluent = isFluent;
            return isFluent;
        }

        private static bool IsParlotNamespace(ExpressionSyntax expression)
        {
            return expression is IdentifierNameSyntax identifier && identifier.Identifier.ValueText == "Parlot"
                || expression is AliasQualifiedNameSyntax alias
                    && alias.Alias.Identifier.ValueText == "global"
                    && alias.Name.Identifier.ValueText == "Parlot";
        }

        private static bool IsRuntimeType(SimpleNameSyntax name, bool fluent)
        {
            var arity = name is GenericNameSyntax generic ? generic.Arity : 0;
            return (fluent, name.Identifier.ValueText, arity) switch
            {
                (false, "Scanner" or "Cursor" or "TextPosition" or "TextSpan" or "ParseException"
                    or "ParseError" or "Character" or "CharacterMask" or "Numbers" or "HexConverter" or "ThrowHelper", 0) => true,
                (false, "ParseResult" or "Option", 1) => true,
                (true, "ParseContext" or "NumberOptions", 0) => true,
                (true, "Parser" or "HybridList" or "DelegateParser", 1) => true,
                _ => false,
            };
        }
    }
}
